theme: minima
title: My first blog in GitHub
author: evaalvarez03
email: eva3895@gmail.com
description: This is my first site in Github, I am learning with this course. > # this means to ignore newlines until "baseurl:"
  
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username: eva_alvarez03 # DO NOT include the @ character, or else the build will fail!
github_username:  evaalvarez03 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
